### ISSUE TITLE
Order articles by published date and return number of results

### ISSUE THREAD

**Issue by lisahillebrand** [I-News-Pipeline-HTW-Berlin/Backend#3]
Currently the oldest articles are returned when requesting /articles. Should return articles ordered by date with the newest ones first.

```json
{
  "resultCount": 200,
  "list": [
    {
      "id": "string",
      "site": "string",
      "title": "string",
      "description": "string",
      "intro": "string",
      "text": "string",
      "url": "string"
    }
  ]
}
```

**Comment by drahenprofi** [comment]
The article list is ordered by published_time descending by default now. 
The result count is added to the result object, but it currently only holds the count of the returned articles, not the full count.

**Comment by drahenprofi** [comment]
Result count is correct now, maximum 10000 (from elasticsearch)
