### ISSUE TITLE
Add parameter to filter for newspapers when requesting articles

### ISSUE THREAD

**Issue by lisahillebrand** [I-News-Pipeline-HTW-Berlin/Backend#4]
It should be possible to send multiple newspapers as query parameter. They will be separated by commas.

**Comment by drahenprofi** [comment]
It is now possible to send multiple newspapers and departments as query parameters, the syntax is the following: `/api/articles?newspaper= taz&newspaper=sz`, `/api/articles?department=Politik&department=Sport`
